[tox]
envlist = lint, py{310,311,312,313}
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
    alembic
allowlist_externals = poetry
commands_pre =
    poetry install --no-interaction --quiet
commands =
    pytest tests/ --ignore=tests/test_suite.py -q --cov=sqlalchemy_cubrid --cov-fail-under=95

[testenv:lint]
deps =
    ruff
    bandit[toml]
commands =
    ruff check sqlalchemy_cubrid/
    ruff format --check sqlalchemy_cubrid/
    bandit -c pyproject.toml -r sqlalchemy_cubrid/
